### ISSUE TITLE
Progress on booting

### ISSUE THREAD

**Issue by RafayGhafoor** [MomoYuuki/android_device_lge_timelm#1]
Hi, I wanted to ask if you were able to boot this device? Also, if you're available on telegram. Thanks

**Comment by MomoYuuki** [comment]
It can't be started at the moment, the problem at the moment is that the DATA can't be decrypted and the keymaster and keystore can't be started, this is my telegram, if you can help me, feel free to contact me, t.me/MomoYuuki



---Original---
From: "Muhammad Rafay ***@***.***&gt;
Date: Fri, Apr 26, 2024 18:46 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [MomoYuuki/android_device_lge_timelm] Progress on booting (Issue #1)




 
Hi, I wanted to ask if you were able to boot this device? Also, if you're available on telegram. Thanks
